export const INIT_LOCATION_HEIRARCHY_DROPDOWN_START = 'INIT_LOCATION_HEIRARCHY_DROPDOWN_START';
export const INIT_LOCATION_HEIRARCHY_DROPDOWN_SUCCESS = 'INIT_LOCATION_HEIRARCHY_DROPDOWN_SUCCESS';
export const INIT_LOCATION_HEIRARCHY_DROPDOWN_FAIL = 'INIT_LOCATION_HEIRARCHY_DROPDOWN_FAIL';

export const INIT_DIVISON_LIST_DROPDOWN_START = 'INIT_DIVISON_LIST_DROPDOWN_START';
export const INIT_DIVISON_LIST_DROPDOWN_SUCCESS = 'INIT_DIVISON_LIST_DROPDOWN_SUCCESS';
export const INIT_DIVISON_LIST_DROPDOWN_FAIL = 'INIT_DIVISON_LIST_DROPDOWN_FAIL';

export const INIT_LOCATION_DROPDOWN_START = 'INIT_LOCATION_DROPDOWN_START'
export const INIT_LOCATION_DROPDOWN_SUCCESS = 'INIT_LOCATION_DROPDOWN_SUCCESS'
export const INIT_LOCATION_DROPDOWN_FAIL = 'INIT_LOCATION_DROPDOWN_FAIL'

export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
