// global
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

//DB Install actions
export const RUN_DB_INSTALL_START = 'RUN_DB_INSTALL_START';
export const RUN_DB_INSTALL_SUCCESS = 'RUN_DB_INSTALL_SUCCESS';
export const RUN_DB_INSTALL_FAIL = 'RUN_DB_INSTALL_FAIL';

//Dashboard Actions
export const INIT_DASHBOARD_START = 'INIT_DASHBOARD_START';
export const INIT_DASHBOARD_SUCCESS = 'INIT_DASHBOARD_SUCCESS';
export const INIT_DASHBOARD_FAIL = 'INIT_DASHBOARD_FAIL';

export const HOSPITAL_DAILY_DASHBOARD_START = 'HOSPITAL_DAILY_DASHBOARD_START';
export const HOSPITAL_DAILY_DASHBOARD_SUCCESS =
  'HOSPITAL_DAILY_DASHBOARD_SUCCESS';
export const HOSPITAL_DAILY_DASHBOARD_FAIL = 'HOSPITAL_DAILY_DASHBOARD_FAIL';

export const HOSPITAL_MONTHLY_DASHBOARD_START =
  'HOSPITAL_MONTHLY_DASHBOARD_START';
export const HOSPITAL_MONTHLY_DASHBOARD_SUCCESS =
  'HOSPITAL_MONTHLY_DASHBOARD_SUCCESS';
export const HOSPITAL_MONTHLY_DASHBOARD_FAIL =
  'HOSPITAL_MONTHLY_DASHBOARD_FAIL';

export const HOSPITAL_DAILY_DETAILS_START = 'HOSPITAL_DAILY_DETAILS_START';
export const HOSPITAL_DAILY_DETAILS_SUCCESS = 'HOSPITAL_DAILY_DETAILS_SUCCESS';
export const HOSPITAL_DAILY_DETAILS_FAIL = 'HOSPITAL_DAILY_DETAILS_FAIL';

export const HOSPITAL_MONTHLY_DETAILS_START = 'HOSPITAL_MONTHLY_DETAILS_START';
export const HOSPITAL_MONTHLY_DETAILS_SUCCESS =
  'HOSPITAL_MONTHLY_DETAILS_SUCCESS';
export const HOSPITAL_MONTHLY_DETAILS_FAIL = 'HOSPITAL_MONTHLY_DETAILS_FAIL';

//Master Sync actions
export const MASTER_SYNC_START = 'MASTER_SYNC_START';
export const MASTER_SYNC_SUCCESS = 'MASTER_SYNC_SUCCESS';
export const MASTER_SYNC_FAIL = 'MASTER_SYNC_FAIL';

//Auth Actions
export const AUTHENTICATION_START_ACTION = 'AUTHENTICATION_START_ACTION';
export const AUTHENTICATION_SUCCESS_ACTION = 'AUTHENTICATION_SUCCESS_ACTION';
export const AUTHENTICATION_FAIL_ACTION = 'AUTHENTICATION_FAIL_ACTION';

//Common Actions
export const LOAD_EMPLOYEE_START_ACTION = 'LOAD_EMPLOYEE_START_ACTION';
export const LOAD_EMPLOYEE_SUCCESS_ACTION = 'LOAD_EMPLOYEE_SUCCESS_ACTION';
export const LOAD_EMPLOYEE_FAIL_ACTION = 'LOAD_EMPLOYEE_FAIL_ACTION';

export const LOAD_BEATS_START_ACTION = 'LOAD_BEATS_START_ACTION';
export const LOAD_BEATS_SUCCESS_ACTION = 'LOAD_BEATS_SUCCESS_ACTION';
export const LOAD_BEATS_FAIL_ACTION = 'LOAD_BEATS_FAIL_ACTION';

export const LOAD_DOCTORS_START_ACTION = 'LOAD_DOCTORS_START_ACTION';
export const LOAD_DOCTORS_SUCCESS_ACTION = 'LOAD_DOCTORS_SUCCESS_ACTION';
export const LOAD_DOCTORS_FAIL_ACTION = 'LOAD_DOCTORS_FAIL_ACTION';

//Planning Actions
export const INIT_PLAN_START_ACTION = 'INIT_PLAN_START_ACTION';
export const INIT_PLAN_SUCCESS_ACTION = 'INIT_PLAN_SUCCESS_ACTION';
export const INIT_PLAN_FAIL_ACTION = 'INIT_PLAN_FAIL_ACTION';

export const INIT_NON_CALL_START = 'INIT_NON_CALL_START';
export const INIT_NON_CALL_SUCCESS = 'INIT_NON_CALL_SUCCESS';
export const INIT_NON_CALL_FAIL = 'INIT_NON_CALL_FAIL';

export const FETCH_PLAN_SUMMARY_START = 'FETCH_PLAN_SUMMARY_START';
export const FETCH_PLAN_SUMMARY_SUCCESS = 'FETCH_PLAN_SUMMARY_SUCCESS';
export const FETCH_PLAN_SUMMARY_FAIL = 'FETCH_PLAN_SUMMARY_FAIL';

export const CHANGE_PLAN_TYPE_START_ACTION = 'CHANGE_PLAN_TYPE_START_ACTION';
export const CHANGE_PLAN_TYPE_SUCCESS_ACTION =
  'CHANGE_PLAN_TYPE_SUCCESS_ACTION';
export const CHANGE_PLAN_TYPE_FAIL_ACTION = 'CHANGE_PLAN_TYPE_FAIL_ACTION';

export const ADD_BEATS_TO_PLAN_START_ACTION = 'ADD_BEATS_TO_PLAN_START_ACTION';
export const ADD_BEATS_TO_PLAN_SUCCESS_ACTION =
  'ADD_BEATS_TO_PLAN_SUCCESS_ACTION';
export const ADD_BEATS_TO_PLAN_FAIL_ACTION = 'ADD_BEATS_TO_PLAN_FAIL_ACTION';

export const ADD_DOCTORS_TO_PLAN_START_ACTION =
  'ADD_DOCTORS_TO_PLAN_START_ACTION';
export const ADD_DOCTORS_TO_PLAN_SUCCESS_ACTION =
  'ADD_DOCTORS_TO_PLAN_SUCCESS_ACTION';
export const ADD_DOCTORS_TO_PLAN_FAIL_ACTION =
  'ADD_DOCTORS_TO_PLAN_FAIL_ACTION';

export const REMOVE_DOCTOR_FROM_PLAN_START = 'REMOVE_DOCTOR_FROM_PLAN_START';
export const REMOVE_DOCTOR_FROM_PLAN_SUCCESS =
  'REMOVE_DOCTOR_FROM_PLAN_SUCCESS';
export const REMOVE_DOCTOR_FROM_PLAN_FAIL = 'REMOVE_DOCTOR_FROM_PLAN_FAIL';

export const SAVE_DOCTOR_TO_PLAN_START = 'SAVE_DOCTOR_TO_PLAN_START';
export const SAVE_DOCTOR_TO_PLAN_SUCCESS = 'SAVE_DOCTOR_TO_PLAN_SUCCESS';
export const SAVE_DOCTOR_TO_PLAN_FAIL = 'SAVE_DOCTOR_TO_PLAN_FAIL';

export const SAVE_NON_CALL_TO_PLAN_START = 'SAVE_NON_CALL_TO_PLAN_START';
export const SAVE_NON_CALL_TO_PLAN_SUCCESS = 'SAVE_NON_CALL_TO_PLAN_SUCCESS';
export const SAVE_NON_CALL_TO_PLAN_FAIL = 'SAVE_NON_CALL_TO_PLAN_FAIL';

//Call reporting

export const CHANGE_CALL_TYPE_LIST_START = 'CHANGE_CALL_TYPE_LIST_START';
export const CHANGE_CALL_TYPE_LIST_SUCCESS = 'CHANGE_CALL_TYPE_LIST_SUCCESS';
export const CHANGE_CALL_TYPE_LIST_FAIL = 'CHANGE_CALL_TYPE_LIST_FAIL';

export const SAVE_NON_CALL_START = 'SAVE_NON_CALL_START';
export const SAVE_NON_CALL_SUCCESS = 'SAVE_NON_CALL_SUCCESS';
export const SAVE_NON_CALL_FAIL = 'SAVE_NON_CALL_FAIL';

export const HANDLE_PHYSICAL_DIGITAL_SWITCH_START =
  'HANDLE_PHYSICAL_DIGITAL_SWITCH_START';
export const HANDLE_PHYSICAL_DIGITAL_SWITCH_SUCCESS =
  'HANDLE_PHYSICAL_DIGITAL_SWITCH_SUCCESS';
export const HANDLE_PHYSICAL_DIGITAL_SWITCH_FAIL =
  'HANDLE_PHYSICAL_DIGITAL_SWITCH_FAIL';


export const RCPA_CHANGE_START = 'RCPA_CHANGE_START';
export const RCPA_CHANGE_SUCCESS = 'RCPA_CHANGE_SUCCESS';
export const RCPA_CHANGE_FAIL = 'RCPA_CHANGE_FAIL';

export const DELETE_RCPA_START = 'DELETE_RCPA_START';
export const DELETE_RCPA_SUCCESS = 'DELETE_RCPA_SUCCESS';
export const DELETE_RCPA_FAIL = 'DELETE_RCPA_FAIL';

//DIGITAL video call
export const LOAD_DIGITAL_TEMPLATE_START = 'LOAD_DIGITAL_TEMPLATE_START';
export const LOAD_DIGITAL_TEMPLATE_SUCCESS = 'LOAD_DIGITAL_TEMPLATE_SUCCESS';
export const LOAD_DIGITAL_TEMPLATE_FAIL = 'LOAD_DIGITAL_TEMPLATE_FAIL';

export const SAVE_VIDEO_CALL_START = 'SAVE_VIDEO_CALL_START';
export const SAVE_VIDEO_CALL_SUCCESS = 'SAVE_VIDEO_CALL_SUCCESS';
export const SAVE_VIDEO_CALL_FAIL = 'SAVE_VIDEO_CALL_FAIL';

export const SAVE_VISIT_DATA_START = 'SAVE_VISIT_DATA_START';
export const SAVE_VISIT_DATA_SUCCESS = 'SAVE_VISIT_DATA_SUCCESS';
export const SAVE_VISIT_DATA_FAIL = 'SAVE_VISIT_DATA_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

//Leaves
export const INIT_LEAVE_START = 'INIT_LEAVE_START';
export const INIT_LEAVE_SUCCESS = 'INIT_LEAVE_SUCCESS';
export const INIT_LEAVE_FAIL = 'INIT_LEAVE_FAIL';

export const LEAVE_APPLY_START = 'LEAVE_APPLY_START';
export const LEAVE_APPLY_SUCCESS = 'LEAVE_APPLY_SUCCESS';
export const LEAVE_APPLY_FAIL = 'LEAVE_APPLY_FAIL';

//Settings
export const INIT_SETTINGS_VIEW_START = 'INIT_SETTINGS_VIEW_START';
export const INIT_SETTINGS_VIEW_SUCCESS = 'INIT_SETTINGS_VIEW_SUCCESS';
export const INIT_SETTINGS_VIEW_FAIL = 'INIT_SETTINGS_VIEW_FAIL';

export const SYNC_NOW_START = 'SYNC_NOW_START';
export const SYNC_NOW_SUCCESS = 'SYNC_NOW_SUCCESS';
export const SYNC_NOW_FAIL = 'SYNC_NOW_FAIL';


//Keyaccounts
export const INIT_HOSPITAL_LIST_START = 'INIT_HOSPITAL_LIST_START';
export const INIT_HOSPITAL_LIST_SUCCESS = 'INIT_HOSPITAL_LIST_SUCCESS';
export const INIT_HOSPITAL_LIST_FAIL = 'INIT_HOSPITAL_LIST_FAIL';

export const HOSPITAL_ENTRY_START = 'HOSPITAL_ENTRY_START';
export const HOSPITAL_ENTRY_SUCCESS = 'HOSPITAL_ENTRY_SUCCESS';
export const HOSPITAL_ENTRY_FAIL = 'HOSPITAL_ENTRY_FAIL';

export const INIT_HOSPITAL_ENTRY_START = 'INIT_HOSPITAL_ENTRY_START';
export const INIT_HOSPITAL_ENTRY_SUCCESS = 'INIT_HOSPITAL_ENTRY_SUCCESS';
export const INIT_HOSPITAL_ENTRY_FAIL = 'INIT_HOSPITAL_ENTRY_FAIL';

export const DELETE_HOSPITAL_ENTRY_START = 'DELETE_HOSPITAL_ENTRY_START';
export const DELETE_HOSPITAL_ENTRY_SUCCESS = 'DELETE_HOSPITAL_ENTRY_SUCCESS';
export const DELETE_HOSPITAL_ENTRY_FAIL = 'DELETE_HOSPITAL_ENTRY_FAIL';

export const INIT_HOSPITAL_DAILY_ENTRY_START =
  'INIT_HOSPITAL_DAILY_ENTRY_START';
export const INIT_HOSPITAL_DAILY_ENTRY_SUCCESS =
  'INIT_HOSPITAL_DAILY_ENTRY_SUCCESS';
export const INIT_HOSPITAL_DAILY_ENTRY_FAIL = 'INIT_HOSPITAL_DAILY_ENTRY_FAIL';

export const SAVE_HOSPITAL_DAILY_ENTRY_START =
  'SAVE_HOSPITAL_DAILY_ENTRY_START';
export const SAVE_HOSPITAL_DAILY_ENTRY_SUCCESS =
  'SAVE_HOSPITAL_DAILY_ENTRY_SUCCESS';
export const SAVE_HOSPITAL_DAILY_ENTRY_FAIL = 'SAVE_HOSPITAL_DAILY_ENTRY_FAIL';

//Background sync
export const BG_SYNC_START = 'BG_SYNC_START';
export const BG_SYNC_SUCCESS = 'BG_SYNC_SUCCESS';
export const BG_SYNC_FAIL = 'BG_SYNC_FAIL';

//Approval
export const REFRESH_PATIENT_APPROVAL_START = 'REFRESH_PATIENT_APPROVAL_START';
export const REFRESH_PATIENT_APPROVAL_SUCCESS =
  'REFRESH_PATIENT_APPROVAL_SUCCESS';
export const REFRESH_PATIENT_APPROVAL_FAIL = 'REFRESH_PATIENT_APPROVAL_FAIL';

export const APPROVE_PATIENT_RCPA_START = 'APPROVE_PATIENT_RCPA_START';
export const APPROVE_PATIENT_RCPA_SUCCESS = 'APPROVE_PATIENT_RCPA_SUCCESS';
export const APPROVE_PATIENT_RCPA_FAIL = 'APPROVE_PATIENT_RCPA_FAIL';

export const REJECT_PATIENT_RCPA_START = 'REJECT_PATIENT_RCPA_START';
export const REJECT_PATIENT_RCPA_SUCCESS = 'REJECT_PATIENT_RCPA_SUCCESS';
export const REJECT_PATIENT_RCPA_FAIL = 'REJECT_PATIENT_RCPA_FAIL';

//Transaction sync
export const TRANSACTION_SYNC_START = 'TRANSACTION_SYNC_START';
export const TRANSACTION_SYNC_SUCCESS = 'TRANSACTION_SYNC_SUCCESS';
export const TRANSACTION_SYNC_FAIL = 'TRANSACTION_SYNC_FAIL';

//Manager planning
export const LOAD_MY_TEAM_PLAN_START = 'LOAD_MY_TEAM_PLAN_START';
export const LOAD_MY_TEAM_PLAN_SUCCESS = 'LOAD_MY_TEAM_PLAN_SUCCESS';
export const LOAD_MY_TEAM_PLAN_FAIL = 'LOAD_MY_TEAM_PLAN_FAIL';

//Marketing Activity
export const LOAD_MASTERS_FOR_MKT_START = 'LOAD_MASTERS_FOR_MKT_START';
export const LOAD_MASTERS_FOR_MKT_SUCCESS = 'LOAD_MASTERS_FOR_MKT_SUCCESS';
export const LOAD_MASTERS_FOR_MKT_FAIL = 'LOAD_MASTERS_FOR_MKT_FAIL';

//Manager Tour plan
export const SAVE_MANAGER_PLAN_TO_LOCAL_START =
  'SAVE_MANAGER_PLAN_TO_LOCAL_START';
export const SAVE_MANAGER_PLAN_TO_LOCAL_SUCCESS =
  'SAVE_MANAGER_PLAN_TO_LOCAL_SUCCESS';
export const SAVE_MANAGER_PLAN_TO_LOCAL_FAIL =
  'SAVE_MANAGER_PLAN_TO_LOCAL_FAIL';

export const INIT_MANAGER_PLAN_TO_LOCAL_START =
  'INIT_MANAGER_PLAN_TO_LOCAL_START';
export const INIT_MANAGER_PLAN_TO_LOCAL_SUCCESS =
  'INIT_MANAGER_PLAN_TO_LOCAL_SUCCESS';
export const INIT_MANAGER_PLAN_TO_LOCAL_FAIL =
  'INIT_MANAGER_PLAN_TO_LOCAL_FAIL';

export const RESET_TOUR_PLAN_START = 'RESET_TOUR_PLAN_START';
export const RESET_TOUR_PLAN_SUCCESS = 'RESET_TOUR_PLAN_SUCCESS';
export const RESET_TOUR_PLAN_FAIL = 'RESET_TOUR_PLAN_FAIL';
