export const SINGLE_RCPA_INIT_START = 'SINGLE_RCPA_INIT_START';
export const SINGLE_RCPA_INIT_SUCCESS = 'SINGLE_RCPA_INIT_SUCCESS';
export const SINGLE_RCPA_INIT_FAIL = 'SINGLE_RCPA_INIT_FAIL';

export const SINGLE_RCPA_CHANGE_START = 'SINGLE_RCPA_CHANGE_START';
export const SINGLE_RCPA_CHANGE_SUCCESS = 'SINGLE_RCPA_CHANGE_SUCCESS';
export const SINGLE_RCPA_CHANGE_FAIL = 'SINGLE_RCPA_CHANGE_FAIL';
