export const SFC_SEARCH_START = 'SFC_SEARCH_START';
export const SFC_SEARCH_SUCCESS = 'SFC_SEARCH_SUCCESS';
export const SFC_SEARCH_FAIL = 'SFC_SEARCH_FAIL';

export const SFC_UPDATE_DISTANCE_START = 'SFC_UPDATE_DISTANCE_START';
export const SFC_UPDATE_DISTANCE_SUCCESS = 'SFC_UPDATE_DISTANCE_SUCCESS';
export const SFC_UPDATE_DISTANCE_FAIL = 'SFC_UPDATE_DISTANCE_FAIL';

export const SFC_CREATE_DISTANCE_START = 'SFC_CREATE_DISTANCE_START';
export const SFC_CREATE_DISTANCE_SUCCESS = 'SFC_CREATE_DISTANCE_SUCCESS';
export const SFC_CREATE_DISTANCE_FAIL = 'SFC_CREATE_DISTANCE_FAIL';

export const SFC_LOAD_TOWNS_START = 'SFC_LOAD_TOWNS_START';
export const SFC_LOAD_TOWNS_SUCCESS = 'SFC_LOAD_TOWNS_SUCCESS';
export const SFC_LOAD_TOWNS_FAIL = 'SFC_LOAD_TOWNS_FAIL';
