import {v4 as uuidv4} from 'uuid';
export const DB_NAME = 'infinity.db';
export const generateId = () => uuidv4();

export const APP_INFO = 'AppInfo';
export const BEAT_MASTER = 'BeatMaster';
export const DOCTOR_MASTER = 'DoctorMaster';
export const TOUR_PLAN = 'TourPlan';
export const TEAM_TOUR_PLAN = 'TeamTourPlan';
export const DIGITAL_CALL_DATA = 'DigitalCallData';
export const JOINEE_MASTER = 'JoineeMaster';
export const CHEMIST_MASTER = 'ChemistMaster';
export const DOCTOR_CHEMIST = 'DoctorChemists';
export const BRAND_MASTER = 'OwnBrandMaster';
export const COMP_BRAND_MASTER = 'CompBrandMaster';
export const RCPA_DATA = 'RCPAData';
export const BRAND_DETAILING = 'BrandDetailing';
export const DIGITAL_TEMPLATES = 'DigitalTemplates';
export const CONTACT_LIST = 'ContactListMaster';
export const NAME_VALUE = 'NameValue';
export const NON_CALL_ACTIVITY = 'NonCallActivity';
export const EMPLOYEE_PROFILE = 'EmployeeProfile';
export const LEAVE_HISTORY = 'LeaveHistory';
export const LEAVE_DETAILS = 'LeaveDetails';
export const SYNC_LOG = 'SyncLog';
export const VISIT_JOINEES = 'VisitJoinees';
export const INPUT_INVENTORY = 'InputInventory';
export const HOSPITAL_MASTER = 'HospitalMaster';
export const HOSPITAL_ENTRY = 'HospitalEntry';
export const HOSPITAL_DAILY_ENTRY = 'HospitalDailyEntry';
export const MY_TEAM = 'MyTeam';
export const ADDRESS_MASTER = 'AddressMaster';
export const FOCUSED_BRAND = 'FocusedBrand';
export const INPUT_DISTRIBUTION = 'InputDistribution';
export const HOSPITAL_DOCTORS = 'HospitalDoctors';
export const DETAILING_AID = 'DetailingAid';
export const PRECALL_PLAN = 'PreCallPlan';
export const DOCTOR_COORDINATES = 'DoctorCoordinates';