export const INIT_DML_REPORT_START = 'INIT_DML_REPORT_START';
export const INIT_DML_REPORT_SUCCESS = 'INIT_DML_REPORT_SUCCESS';
export const INIT_DML_REPORT_FAIL = 'INIT_DML_REPORT_FAIL';

export const FETCH_DML_REPORT_START = 'FETCH_DML_REPORT_START';
export const FETCH_DML_REPORT_SUCCESS = 'FETCH_DML_REPORT_SUCCESS';
export const FETCH_DML_REPORT_FAIL = 'FETCH_DML_REPORT_FAIL';
