
application:
  name: dev
  environment: dev
  enabled: true
  config:
    uploadpath: "/Users/shriramgosavi/codebase/uploads"
    path: "/Users/shriramgosavi/codebase/configs/dev"
    multitenant: true
    sqlServerUserName: SFE_USER
    sqlServerPassword: sfeuser@123
    sqlServerURL: jdbc:sqlserver://192.168.4.181:1433;databaseName=SFE_DB;user=SFE_USER;password=sfeuser@123
    sqlServerDriver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  configdatasource:
    host: "localhost"
    port: 27017
    db: "config"
  cache:
    remote:
      host: localhost
      port: 6379
      timeout: 18000
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/users_config
    username: postgres
    password: postgres
    testConnectionOnCheckout: true
    testConnectionOnCheckin: true
  activemq:
    user: sfa_admin
    password: welcome
    broker: spring.activemq.broker-url=tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=2

logging:
  level:
    root: DEBUG
server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/robust.p12
    key-store-password: welcome
    key-alias: robust
    enabled: true
  http:
    port: 8090
smtp:
  smtp_from: donotreply.sns@neumeriq.com
  smtp_host_name: smtp-mail.outlook.com
  smtp_password: Support@Squer321!
  smtp_port: 587
  smtp_subject: SNS
  smtp_user_name: field.support@squer.co.in

---

application:
  name: prod
  environment: prod
  enabled: false
  config:
    uploadpath: "/infinity/uploads/"
    path: "/disk1/sns/configs/prod"
    multitenant: true
    sqlServerUserName: SFE_USER
    sqlServerPassword: sfeuser@123
    sqlServerURL: jdbc:sqlserver://192.168.4.181:1433;databaseName=SFE_DB;user=SFE_USER;password=sfeuser@123
    sqlServerDriver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  configdatasource:
    host: "localhost"
    port: 27017
    db: "config"
  cache:
    remote:
      host: localhost
      port: 6379
      timeout: 18000
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://10.168.24.99:5432/nu_sfe_config
    username: postgres
    password: Welcome#12345
    testConnectionOnCheckout: true
    testConnectionOnCheckin: true
logging:
  level:
    root: ERROR
server:
  port: 80
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/robust.p12
    key-store-password: welcome
    key-alias: robust
    enabled: true
  http:
    port: 8080
smtp:
  smtp_from: donotreply.sns@neumeriq.com
  smtp_host_name: smtp-mail.outlook.com
  smtp_password: Support@Squer321!
  smtp_port: 587
  smtp_subject: SNS
  smtp_user_name: field.support@squer.co.in

---

application:
  name: pharmeasy
  environment: pharmeasy
  enabled: false
  config:
    uploadpath: "/infinity/uploads/"
    path: "/disk1/sns/configs/prod"
    multitenant: true
    sqlServerUserName: SFE_USER
    sqlServerPassword: sfeuser@123
    sqlServerURL: jdbc:sqlserver://192.168.4.181:1433;databaseName=SFE_DB;user=SFE_USER;password=sfeuser@123
    sqlServerDriver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  configdatasource:
    host: "localhost"
    port: 27017
    db: "config"
  cache:
    remote:
      host: localhost
      port: 6379
      timeout: 18000
spring:
  profiles: pharmeasy
  datasource:
    url: jdbc:postgresql://localhost:5432/nu_sfe_config
    username: postgres
    password: Welcome#12345
    testConnectionOnCheckout: true
    testConnectionOnCheckin: true
logging:
  level:
    root: ERROR
server:
  port: 8090
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/robust.p12
    key-store-password: welcome
    key-alias: robust
    enabled: true
  http:
    port: 8080
smtp:
  smtp_from: donotreply.sns@neumeriq.com
  smtp_host_name: smtp-mail.outlook.com
  smtp_password: Support@Squer321!
  smtp_port: 587
  smtp_subject: SNS
  smtp_user_name: field.support@squer.co.in