export const INIT_INPUT_INVENTORY_START = 'INIT_INPUT_INVENTORY_START';
export const INIT_INPUT_INVENTORY_SUCCESS = 'INIT_INPUT_INVENTORY_SUCCESS';
export const INIT_INPUT_INVENTORY_FAIL = 'INIT_INPUT_INVENTORY_FAIL';

export const DISTRIBUTE_INPUT_START = 'DISTRIBUTE_INPUT_START';
export const DISTRIBUTE_INPUT_SUCCESS = 'DISTRIBUTE_INPUT_SUCCESS';
export const DISTRIBUTE_INPUT_FAIL = 'DISTRIBUTE_INPUT_FAIL';

export const SAVE_INPUT_TO_STATE_START = 'SAVE_INPUT_TO_STATE_START';

export const INIT_INPUT_DISTRIBUTION_START = 'INIT_INPUT_DISTRIBUTION_START';
export const INIT_INPUT_DISTRIBUTION_SUCCESS =
  'INIT_INPUT_DISTRIBUTION_SUCCESS';
export const INIT_INPUT_DISTRIBUTION_FAIL = 'INIT_INPUT_DISTRIBUTION_FAIL';
