package com.squer.sfe.reporting

import com.squer.platform.persistence.AdhocQueryName
import com.squer.platform.persistence.SquerQuery
enum class ReportingQueryName (override val query: AdhocQueryName): SquerQuery {
MTPLN_SELECT (AdhocQueryName("mtpln_select")),
MTPLN_INSERT (AdhocQueryName("mtpln_insert")),
MTPLN_UPDATE (AdhocQueryName("mtpln_update")),
MTPLN_DELETE (AdhocQueryName("mtpln_delete")),
DTVST_SELECT (AdhocQueryName("dtvst_select")),
DTVST_INSERT (AdhocQueryName("dtvst_insert")),
DTVST_UPDATE (AdhocQueryName("dtvst_update")),
DTVST_DELETE (AdhocQueryName("dtvst_delete")),
DTVAT_SELECT (AdhocQueryName("dtvat_select")),
DTVAT_INSERT (AdhocQueryName("dtvat_insert")),
DTVAT_UPDATE (AdhocQueryName("dtvat_update")),
DTVAT_DELETE (AdhocQueryName("dtvat_delete")),
DTVJE_SELECT (AdhocQueryName("dtvje_select")),
DTVJE_INSERT (AdhocQueryName("dtvje_insert")),
DTVJE_UPDATE (AdhocQueryName("dtvje_update")),
DTVJE_DELETE (AdhocQueryName("dtvje_delete")),
DTNCT_SELECT (AdhocQueryName("dtnct_select")),
DTNCT_INSERT (AdhocQueryName("dtnct_insert")),
DTNCT_UPDATE (AdhocQueryName("dtnct_update")),
DTNCT_DELETE (AdhocQueryName("dtnct_delete")),
VACTV_SELECT (AdhocQueryName("vactv_select")),
VACTV_INSERT (AdhocQueryName("vactv_insert")),
VACTV_UPDATE (AdhocQueryName("vactv_update")),
VACTV_DELETE (AdhocQueryName("vactv_delete")),
VDETL_SELECT (AdhocQueryName("vdetl_select")),
VDETL_INSERT (AdhocQueryName("vdetl_insert")),
VDETL_UPDATE (AdhocQueryName("vdetl_update")),
VDETL_DELETE (AdhocQueryName("vdetl_delete")),
VINPT_SELECT (AdhocQueryName("vinpt_select")),
VINPT_INSERT (AdhocQueryName("vinpt_insert")),
VINPT_UPDATE (AdhocQueryName("vinpt_update")),
VINPT_DELETE (AdhocQueryName("vinpt_delete")),
VTPOB_SELECT (AdhocQueryName("vtpob_select")),
VTPOB_INSERT (AdhocQueryName("vtpob_insert")),
VTPOB_UPDATE (AdhocQueryName("vtpob_update")),
VTPOB_DELETE (AdhocQueryName("vtpob_delete")),
VRCPA_SELECT (AdhocQueryName("vrcpa_select")),
VRCPA_INSERT (AdhocQueryName("vrcpa_insert")),
VRCPA_UPDATE (AdhocQueryName("vrcpa_update")),
VRCPA_DELETE (AdhocQueryName("vrcpa_delete")),
DIGVS_SELECT (AdhocQueryName("digvs_select")),
DIGVS_INSERT (AdhocQueryName("digvs_insert")),
DIGVS_UPDATE (AdhocQueryName("digvs_update")),
DIGVS_DELETE (AdhocQueryName("digvs_delete")),
VRCLN_SELECT (AdhocQueryName("vrcln_select")),
VRCLN_INSERT (AdhocQueryName("vrcln_insert")),
VRCLN_UPDATE (AdhocQueryName("vrcln_update")),
VRCLN_DELETE (AdhocQueryName("vrcln_delete")),
MRACT_SELECT (AdhocQueryName("mract_select")),
MRACT_INSERT (AdhocQueryName("mract_insert")),
MRACT_UPDATE (AdhocQueryName("mract_update")),
MRACT_DELETE (AdhocQueryName("mract_delete")),
MRACB_SELECT (AdhocQueryName("mracb_select")),
MRACB_INSERT (AdhocQueryName("mracb_insert")),
MRACB_UPDATE (AdhocQueryName("mracb_update")),
MRACB_DELETE (AdhocQueryName("mracb_delete")),
MRADT_SELECT (AdhocQueryName("mradt_select")),
MRADT_INSERT (AdhocQueryName("mradt_insert")),
MRADT_UPDATE (AdhocQueryName("mradt_update")),
MRADT_DELETE (AdhocQueryName("mradt_delete")),
HSPTG_SELECT (AdhocQueryName("hsptg_select")),
HSPTG_INSERT (AdhocQueryName("hsptg_insert")),
HSPTG_UPDATE (AdhocQueryName("hsptg_update")),
HSPTG_DELETE (AdhocQueryName("hsptg_delete")),
HRCPA_SELECT (AdhocQueryName("hrcpa_select")),
HRCPA_INSERT (AdhocQueryName("hrcpa_insert")),
HRCPA_UPDATE (AdhocQueryName("hrcpa_update")),
HRCPA_DELETE (AdhocQueryName("hrcpa_delete")),
HDRCP_SELECT (AdhocQueryName("hdrcp_select")),
HDRCP_INSERT (AdhocQueryName("hdrcp_insert")),
HDRCP_UPDATE (AdhocQueryName("hdrcp_update")),
HDRCP_DELETE (AdhocQueryName("hdrcp_delete")),
RPTUH_SELECT(AdhocQueryName("rptuh_select")),
/*===ADD TO FILE===*/
ATTENDEE_FOR_PERIOD_SELECT(AdhocQueryName("attendee_for_period_select")),
MANAGER_VISITED_JOINEE_SELECT(AdhocQueryName("manager_visited_joinee_select")),
MANAGER_NOT_VISITED_JOINEE_SELECT(AdhocQueryName("manager_not_visited_joinee_select")),
MANAGER_NOT_VISITED_DATE_JOINEE_SELECT(AdhocQueryName("manager_not_visited_joinee_date_select")),
RCPA_FOR_EMPLOYEE_SELECT(AdhocQueryName("rcpa_for_employee_select")),
INPUT_FOR_EMPLOYEE_SELECT(AdhocQueryName("input_for_employee_select")),
POB_FOR_EMPLOYEE_SELECT(AdhocQueryName("pob_for_employee_select")),
JOINEE_FOR_EMPLOYEE_SELECT(AdhocQueryName("joinee_for_employee_select")),
DETAILING_FOR_EMPLOYEE_SELECT(AdhocQueryName("detailing_for_employee_select")),
DIGITAL_VISIT_FOR_EMPLOYEE_SELECT(AdhocQueryName("digitalVisit_for_employee_select")),
DAILY_HOSPITAL_RCAP_VISIT_COUNT_SELECT(AdhocQueryName("daily_hospital_rcpa_visit_count_select")),
HOSPITAL_STATUS_SELECT(AdhocQueryName("hospital_rcpa_status_select")),
HOSPITAL_RCPA_DASHBOARD_SELF_SELECT(AdhocQueryName("hospital_monthly_dashboard_self_select")),
HOSPITAL_RCPA_FOR_HIERARCHY_SELECT(AdhocQueryName("hospital_rcpa_for_hierarchy_select")),
LOCATION_HOSPITAL_COUNT_SELECT(AdhocQueryName("hierarchy_hospital_select")),
HOSPITAL_DAILY_RCPA_FOR_MANAGER_SELECT(AdhocQueryName("daily_hospital_rcpa_for_manager_select")),
HOSPITAL_DAILY_RCPA_FOR_HIERARCHY_SELECT(AdhocQueryName("hospital_daily_rcpa_for_hierarchy_select")),
MANAGER_JOINT_VISIT_BY_CUSTOMER_SELECT(AdhocQueryName("manager_joint_visit_by_customer_select")),
CHEMIST_CALL_COUNT(AdhocQueryName("chemist_call_count")),
CHEMIST_COVERAGE_COUNT(AdhocQueryName("chemist_coverage_count")),
JOINT_DAYS_COUNT(AdhocQueryName("joint_visit_days_select")),
LEAVE_DAYS_COUNT(AdhocQueryName("leave_day_select")),
HOLIDAY_COUNT_SELECT(AdhocQueryName("holiday_count_select")),
PHYSICAL_DIGITAL_CALL_DAYS_SELECT(AdhocQueryName("physical_digital_call_type_days_select")),
REPROTING_UNLOCK_FOR_USER(AdhocQueryName("unlock_reporting_for_user_update"))
}
