export const INIT_NEW_EXPENSE_START  = 'INIT_NEW_EXPENSE_START';
export const INIT_NEW_EXPENSE_SUCCESS  = 'INIT_NEW_EXPENSE_SUCCESS';
export const INIT_NEW_EXPENSE_FAIL  = 'INIT_NEW_EXPENSE_FAIL';

export const FIND_DISTANCE_TOWNS_START = 'FIND_DISTANCE_TOWNS_START';
export const FIND_DISTANCE_TOWNS_SUCCESS = 'FIND_DISTANCE_TOWNS_SUCCESS';
export const FIND_DISTANCE_TOWNS_FAIL = 'FIND_DISTANCE_TOWNS_FAIL';

export const FIND_ALLOWANCES_FOR_DATE_START = 'FIND_ALLOWANCES_FOR_DATE_START';
export const FIND_ALLOWANCES_FOR_DATE_SUCCESS = 'FIND_ALLOWANCES_FOR_DATE_SUCCESS';
export const FIND_ALLOWANCES_FOR_DATE_FAIL = 'FIND_ALLOWANCES_FOR_DATE_FAIL';

export const SAVE_ROUTE_EXPENSE_START = 'SAVE_ROUTE_EXPENSE_START';
export const SAVE_ROUTE_EXPENSE_SUCCESS = 'SAVE_ROUTE_EXPENSE_SUCCESS';
export const SAVE_ROUTE_EXPENSE_FAIL = 'SAVE_ROUTE_EXPENSE_FAIL';

export const SELECT_EXPENSE_LOCATION_TYPE_START = 'SELECT_EXPENSE_LOCATION_TYPE_START';
export const SELECT_EXPENSE_LOCATION_TYPE_SUCCESS = 'SELECT_EXPENSE_LOCATION_TYPE_SUCCESS';
export const SELECT_EXPENSE_LOCATION_TYPE_FAIL = 'SELECT_EXPENSE_LOCATION_TYPE_FAIL';

export const CLOSE_ROUTE_EXPENSE_DIALOG = 'CLOSE_ROUTE_EXPENSE_DIALOG';
export const CLOSE_TRANSIT_EXPENSE_DIALOG = 'CLOSE_TRANSIT_EXPENSE_DIALOG';

export const SAVE_MISC_LINE_START = 'SAVE_MISC_LINE_START';
export const SAVE_MISC_LINE_SUCCESS = 'SAVE_MISC_LINE_SUCCESS';
export const SAVE_MISC_LINE_FAIL = 'SAVE_MISC_LINE_FAIL';

export const ADD_MISC_LINE = 'ADD_MISC_LINE';
export const ADD_SUNDRIES_LINE = 'ADD_SUNDRIES_LINE';
export const INIT_MISC_LINES = 'INIT_MISC_LINES';

export const SAVE_MEETING_ALLOWANCE_START = 'SAVE_MEETING_ALLOWANCE_START';
export const SAVE_MEETING_ALLOWANCE_SUCCESS = 'SAVE_MEETING_ALLOWANCE_SUCCESS';
export const SAVE_MEETING_ALLOWANCE_FAIL = 'SAVE_MEETING_ALLOWANCE_FAIL';

export const SUBMIT_EXPENSE_START = 'SUBMIT_EXPENSE_START';
export const SUBMIT_EXPENSE_SUCCESS = 'SUBMIT_EXPENSE_SUCCESS';
export const SUBMIT_EXPENSE_FAIL = 'SUBMIT_EXPENSE_FAIL';

export const SEARCH_EXPENSE_START = 'SEARCH_EXPENSE_START';
export const SEARCH_EXPENSE_SUCCESS = 'SEARCH_EXPENSE_SUCCESS';
export const SEARCH_EXPENSE_FAIL = 'SEARCH_EXPENSE_FAIL';

export const SAVE_SUNDRIES_START = 'SAVE_SUNDRIES_START';
export const SAVE_SUNDRIES_SUCCESS = 'SAVE_SUNDRIES_SUCCESS';
export const SAVE_SUNDRIES_FAIL = 'SAVE_SUNDRIES_FAIL';

export const LOAD_SUNDRIES_START = 'LOAD_SUNDRIES_START';
export const LOAD_SUNDRIES_SUCCESS = 'LOAD_SUNDRIES_SUCCESS';
export const LOAD_SUNDRIES_FAIL = 'LOAD_SUNDRIES_FAIL';

export const SAVE_MULTI_SUNDRIES_START = 'SAVE_MULTI_SUNDRIES_START';
export const SAVE_MULTI_SUNDRIES_SUCCESS = 'SAVE_MULTI_SUNDRIES_SUCCESS';
export const SAVE_MULTI_SUNDRIES_FAIL = 'SAVE_MULTI_SUNDRIES_FAIL';

export const SAVE_LODGING_START = 'SAVE_LODGING_START';
export const SAVE_LODGING_SUCCESS = 'SAVE_LODGING_SUCCESS';
export const SAVE_LODGING_FAIL = 'SAVE_LODGING_FAIL';

export const GET_ALL_TOWN_START = 'GET_ALL_TOWN_START';
export const GET_ALL_TOWN_SUCCESS = 'GET_ALL_TOWN_SUCCESS';
export const GET_ALL_TOWN_FAIL = 'GET_ALL_TOWN_FAIL';

export const RESET_EXPENSE_DETAIL_START = 'RESET_EXPENSE_DETAIL_START';
export const RESET_EXPENSE_DETAIL_SUCCESS = 'RESET_EXPENSE_DETAIL_SUCCESS';
export const RESET_EXPENSE_DETAIL_FAIL = 'RESET_EXPENSE_DETAIL_FAIL';
