export const MIS_SEARCH_APPROVAL_START = 'MIS_SEARCH_APPROVAL_START';
export const MIS_SEARCH_APPROVAL_SUCCESS = 'MIS_SEARCH_APPROVAL_SUCCESS';
export const MIS_SEARCH_APPROVAL_FAIL= 'MIS_SEARCH_APPROVAL_FAIL';

export const MIS_APPROVAL_DETAIL_START = 'MIS_APPROVAL_DETAIL_START';
export const MIS_APPROVAL_DETAIL_SUCCESS = 'MIS_APPROVAL_DETAIL_SUCCESS';
export const MIS_APPROVAL_DETAIL_FAIL= 'MIS_APPROVAL_DETAIL_FAIL';

export const APPROVE_EXPENSE_START = 'APPROVE_EXPENSE_START';
export const APPROVE_EXPENSE_SUCCESS = 'APPROVE_EXPENSE_SUCCESS';
export const APPROVE_EXPENSE_FAIL = 'APPROVE_EXPENSE_FAIL';

export const ROUTE_EMPLOYEE_DATE_START = 'ROUTE_EMPLOYEE_DATE_START';
export const ROUTE_EMPLOYEE_DATE_SUCCESS = 'ROUTE_EMPLOYEE_DATE_SUCCESS';
export const ROUTE_EMPLOYEE_DATE_FAIL = 'ROUTE_EMPLOYEE_DATE_FAIL';

export const RESET_EXPENSE_APPROVAL = 'RESET_EXPENSE_APPROVAL';
