package com.squer.sfe.expense

import com.squer.platform.persistence.AdhocQueryName
import com.squer.platform.persistence.SquerQuery
enum class ExpenseQueryName (override val query: AdhocQueryName): SquerQuery {
ALWNC_SELECT (AdhocQueryName("alwnc_select")),
ALWNC_INSERT (AdhocQueryName("alwnc_insert")),
ALWNC_UPDATE (AdhocQueryName("alwnc_update")),
ALWNC_DELETE (AdhocQueryName("alwnc_delete")),
DISTN_SELECT (AdhocQueryName("distn_select")),
DISTN_INSERT (AdhocQueryName("distn_insert")),
DISTN_UPDATE (AdhocQueryName("distn_update")),
DISTN_DELETE (AdhocQueryName("distn_delete")),
EXPMT_SELECT (AdhocQueryName("expmt_select")),
EXPMT_INSERT (AdhocQueryName("expmt_insert")),
EXPMT_UPDATE (AdhocQueryName("expmt_update")),
EXPMT_DELETE (AdhocQueryName("expmt_delete")),
EXPDT_SELECT (AdhocQueryName("expdt_select")),
EXPDT_INSERT (AdhocQueryName("expdt_insert")),
EXPDT_UPDATE (AdhocQueryName("expdt_update")),
EXPDT_DELETE (AdhocQueryName("expdt_delete")),
ROUTS_SELECT (AdhocQueryName("routs_select")),
ROUTS_INSERT (AdhocQueryName("routs_insert")),
ROUTS_UPDATE (AdhocQueryName("routs_update")),
ROUTS_DELETE (AdhocQueryName("routs_delete")),
/*===ADD TO FILE===*/
EXPENSE_VISIT_COUNT_SELECT(AdhocQueryName("expense_visit_count_select")),
EXPENSE_DAILY_VISIT_TYPE_SELECT(AdhocQueryName("expense_daily_visit_type_select")),
EXPENSE_VISITED_TOWNS_SELECT(AdhocQueryName("expense_visited_towns_select")),
EXPENSE_ALLOWANCE_SELECT(AdhocQueryName("expense_allowance_select")),
EXPENSE_DISTANCE_SELECT(AdhocQueryName("expense_distance_select")),
EXPENSE_ROUTE_SELECT(AdhocQueryName("expense_routes_select")),
EXPENSE_CATEGORY_ALLOWANCE_SELECT(AdhocQueryName("expense_category_allowance_select")),
EXPENSE_ALLOWANCE_CONVEYANCE_SELECT(AdhocQueryName("elcal_select")),
EXPENSE_ALLOWANCE_CONVENYANCE_INSERT(AdhocQueryName("elcal_insert")),
EXPENSE_ALLOWANCE_CONVENYANCE_DELETE(AdhocQueryName("elcal_detail_delete")),
EXPENSE_DOCUMENT_BY_DATE(AdhocQueryName("documents_by_date_select")),
EXPENSE_CLAIMED_AMOUNT(AdhocQueryName("expense_sum_select")),
EXPAA_SELECT(AdhocQueryName("expaa_select")),
EXPAA_ADHOC_UPDATE(AdhocQueryName("allowace_amount_update")),
ALLOWANCE_AMOUNT_DELETE(AdhocQueryName("allowance_amount_delete")),
ALLOWANCE_AMOUNT_APPROVE_UPDATE(AdhocQueryName("allowance_amount_approve_update")),
EXPENSE_APPROVED_SELECT(AdhocQueryName("expense_approved_select")),
CONSOLIDATED_EXPENSE_MASTER_SELECT(AdhocQueryName("consolidation_expense_master_select")),
CONSOLIDATED_EXPENSE_DETAILS_SELECT(AdhocQueryName("consolidation_expense_details_select")),
EXPENSE_ALLOWANCE_CATEGORY_SELECT(AdhocQueryName("expense_category_select")),
CONSOLIDATED_EXPENSE_CLAIMED_AMOUNT_SELECT(AdhocQueryName("consolidated_expense_claimed_amount_select")),
EXPENSE_FOR_EMPLOYEE_CODE_MONTH_SELECT(AdhocQueryName("expense_by_employee_code_month_select")),
EXPENSE_APPROVAL_AMOUNT_DELETE(AdhocQueryName("expense_approval_amount_delete")),
EXPENSE_APPROVAL_DELETE(AdhocQueryName("expense_approval_delete")),
CONSOLIDATED_EXPENSE_TYPE_SELECT(AdhocQueryName("consolidated_expense_type_select")),
CONSOLIDATED_EXPENSE_MANAGER_APPROVE_DATE(AdhocQueryName("consolidated_expense_manager_approval_date")),
CONSOLIDATED_EXPENSE_SUBMISSION_DATE(AdhocQueryName("consolidated_expense_submission_date_select"))
;}
