package com.squer.sfe.common

import com.squer.platform.persistence.AdhocQueryName
import com.squer.platform.persistence.SquerQuery
enum class CommonQueryName (override val query: AdhocQueryName): SquerQuery {
EMPLY_SELECT (AdhocQueryName("emply_select")),
EMPLY_INSERT (AdhocQueryName("emply_insert")),
EMPLY_UPDATE (AdhocQueryName("emply_update")),
EMPLY_DELETE (AdhocQueryName("emply_delete")),
LOCAT_SELECT (AdhocQueryName("locat_select")),
LOCAT_INSERT (AdhocQueryName("locat_insert")),
LOCAT_UPDATE (AdhocQueryName("locat_update")),
LOCAT_DELETE (AdhocQueryName("locat_delete")),
ADDRS_SELECT (AdhocQueryName("addrs_select")),
ADDRS_INSERT (AdhocQueryName("addrs_insert")),
ADDRS_UPDATE (AdhocQueryName("addrs_update")),
ADDRS_DELETE (AdhocQueryName("addrs_delete")),
BRAND_SELECT (AdhocQueryName("brand_select")),
BRAND_INSERT (AdhocQueryName("brand_insert")),
BRAND_UPDATE (AdhocQueryName("brand_update")),
BRAND_DELETE (AdhocQueryName("brand_delete")),
CHMST_SELECT (AdhocQueryName("chmst_select")),
CHMST_INSERT (AdhocQueryName("chmst_insert")),
CHMST_UPDATE (AdhocQueryName("chmst_update")),
CHMST_DELETE (AdhocQueryName("chmst_delete")),
CONTC_SELECT (AdhocQueryName("contc_select")),
CONTC_INSERT (AdhocQueryName("contc_insert")),
CONTC_UPDATE (AdhocQueryName("contc_update")),
CONTC_DELETE (AdhocQueryName("contc_delete")),
DIVSN_SELECT (AdhocQueryName("divsn_select")),
DIVSN_INSERT (AdhocQueryName("divsn_insert")),
DIVSN_UPDATE (AdhocQueryName("divsn_update")),
DIVSN_DELETE (AdhocQueryName("divsn_delete")),
DOCTR_SELECT (AdhocQueryName("doctr_select")),
DOCTR_INSERT (AdhocQueryName("doctr_insert")),
DOCTR_UPDATE (AdhocQueryName("doctr_update")),
DOCTR_DELETE (AdhocQueryName("doctr_delete")),
DOCMT_SELECT (AdhocQueryName("docmt_select")),
DOCMT_INSERT (AdhocQueryName("docmt_insert")),
DOCMT_UPDATE (AdhocQueryName("docmt_update")),
DOCMT_DELETE (AdhocQueryName("docmt_delete")),
EMPHS_SELECT (AdhocQueryName("emphs_select")),
EMPHS_INSERT (AdhocQueryName("emphs_insert")),
EMPHS_UPDATE (AdhocQueryName("emphs_update")),
EMPHS_DELETE (AdhocQueryName("emphs_delete")),
JOBRL_SELECT (AdhocQueryName("jobrl_select")),
JOBRL_INSERT (AdhocQueryName("jobrl_insert")),
JOBRL_UPDATE (AdhocQueryName("jobrl_update")),
JOBRL_DELETE (AdhocQueryName("jobrl_delete")),
LOCTT_SELECT (AdhocQueryName("loctt_select")),
LOCTT_INSERT (AdhocQueryName("loctt_insert")),
LOCTT_UPDATE (AdhocQueryName("loctt_update")),
LOCTT_DELETE (AdhocQueryName("loctt_delete")),
PRCDT_SELECT (AdhocQueryName("prcdt_select")),
PRCDT_INSERT (AdhocQueryName("prcdt_insert")),
PRCDT_UPDATE (AdhocQueryName("prcdt_update")),
PRCDT_DELETE (AdhocQueryName("prcdt_delete")),
RETLR_SELECT (AdhocQueryName("retlr_select")),
RETLR_INSERT (AdhocQueryName("retlr_insert")),
RETLR_UPDATE (AdhocQueryName("retlr_update")),
RETLR_DELETE (AdhocQueryName("retlr_delete")),
STATE_SELECT (AdhocQueryName("state_select")),
STATE_INSERT (AdhocQueryName("state_insert")),
STATE_UPDATE (AdhocQueryName("state_update")),
STATE_DELETE (AdhocQueryName("state_delete")),
STCKT_SELECT (AdhocQueryName("stckt_select")),
STCKT_INSERT (AdhocQueryName("stckt_insert")),
STCKT_UPDATE (AdhocQueryName("stckt_update")),
STCKT_DELETE (AdhocQueryName("stckt_delete")),
SYSLV_SELECT (AdhocQueryName("syslv_select")),
SYSLV_INSERT (AdhocQueryName("syslv_insert")),
SYSLV_UPDATE (AdhocQueryName("syslv_update")),
SYSLV_DELETE (AdhocQueryName("syslv_delete")),
TOWNS_SELECT (AdhocQueryName("towns_select")),
TOWNS_INSERT (AdhocQueryName("towns_insert")),
TOWNS_UPDATE (AdhocQueryName("towns_update")),
TOWNS_DELETE (AdhocQueryName("towns_delete")),
BEATS_SELECT (AdhocQueryName("beats_select")),
BEATS_INSERT (AdhocQueryName("beats_insert")),
BEATS_UPDATE (AdhocQueryName("beats_update")),
BEATS_DELETE (AdhocQueryName("beats_delete")),
EMPRF_SELECT (AdhocQueryName("emprf_select")),
EMPRF_INSERT (AdhocQueryName("emprf_insert")),
EMPRF_UPDATE (AdhocQueryName("emprf_update")),
EMPRF_DELETE (AdhocQueryName("emprf_delete")),
RPACT_SELECT (AdhocQueryName("rpact_select")),
RPACT_INSERT (AdhocQueryName("rpact_insert")),
RPACT_UPDATE (AdhocQueryName("rpact_update")),
RPACT_DELETE (AdhocQueryName("rpact_delete")),
DOCPU_SELECT (AdhocQueryName("docpu_select")),
DOCPU_INSERT (AdhocQueryName("docpu_insert")),
DOCPU_UPDATE (AdhocQueryName("docpu_update")),
DOCPU_DELETE (AdhocQueryName("docpu_delete")),
DICTM_SELECT (AdhocQueryName("dictm_select")),
DICTM_INSERT (AdhocQueryName("dictm_insert")),
DICTM_UPDATE (AdhocQueryName("dictm_update")),
DICTM_DELETE (AdhocQueryName("dictm_delete")),
MRACT_SELECT (AdhocQueryName("mract_select")),
MRACT_INSERT (AdhocQueryName("mract_insert")),
MRACT_UPDATE (AdhocQueryName("mract_update")),
MRACT_DELETE (AdhocQueryName("mract_delete")),
HSPTL_SELECT (AdhocQueryName("hsptl_select")),
HSPTL_INSERT (AdhocQueryName("hsptl_insert")),
HSPTL_UPDATE (AdhocQueryName("hsptl_update")),
HSPTL_DELETE (AdhocQueryName("hsptl_delete")),
HOLDY_SELECT (AdhocQueryName("holdy_select")),
HOLDY_INSERT (AdhocQueryName("holdy_insert")),
HOLDY_UPDATE (AdhocQueryName("holdy_update")),
HOLDY_DELETE (AdhocQueryName("holdy_delete")),
HLDTL_SELECT (AdhocQueryName("hldtl_select")),
HLDTL_INSERT (AdhocQueryName("hldtl_insert")),
HLDTL_UPDATE (AdhocQueryName("hldtl_update")),
HLDTL_DELETE (AdhocQueryName("hldtl_delete")),
DOCAT_SELECT (AdhocQueryName("docat_select")),
DOCAT_INSERT (AdhocQueryName("docat_insert")),
DOCAT_UPDATE (AdhocQueryName("docat_update")),
DOCAT_DELETE (AdhocQueryName("docat_delete")),
/*===ADD TO FILE===*/
EMPLOYEE_PROFILE_SELECT (AdhocQueryName("employee_profile_select")),
DOCTOR_FOR_HIERARCHY_SELECT(AdhocQueryName("doctors_for_hierarchy_select")),
DOCTOR_CONTACT_FOR_HIERARCHY_SELECT(AdhocQueryName("doctor_contact_for_hierarchy_select")),
DOCTOR_ADDRESS_FOR_HIERARCHY_SELECT(AdhocQueryName("doctor_address_for_hierarchy_select")),
CHEMIST_FOR_HIERARCHY_SELECT(AdhocQueryName("chemist_for_hierarchy_select")),
CHEMIST_CONTACT_FOR_HIERARCHY_SELECT(AdhocQueryName("chemist_contact_for_hierarchy_select")),
CHEMIST_ADDRESS_FOR_HIERARCHY_SELECT(AdhocQueryName("chemist_address_for_hierarchy_select")),
DOCTOR_FOR_CHEMIST_SELECT(AdhocQueryName("doctors_for_chemist_select")),
HOSPITAL_MASTER_FOR_HIERARCHY_SELECT(AdhocQueryName("hospital_master_for_hierarchy_select")),
DOCTOR_FOR_HOSPITAL_SELECT(AdhocQueryName("doctors_for_hospital_select")),
MY_TEAM_SELECT(AdhocQueryName("my_team_select")),
MY_MANAGER_SELECT(AdhocQueryName("my_managers_select")),
LOCATION_TEMPLATE_SELECT(AdhocQueryName("location_template_select")),
LOCATION_MARKETING_ACTIVITY_SELECT(AdhocQueryName("location_marketing_activity_select")),
LOCATION_HOSPITAL_SELECT(AdhocQueryName("location_hospital_select")),
HOSPITAL_TARGET_FOR_MANAGER(AdhocQueryName("hospital_target_for_manager_select")),
HOSPITAL_FOR_HIERARCHY_SELECT(AdhocQueryName("hospital_for_hierarchy_select")),
PRODUCT_FOR_LOCATION_SELECT(AdhocQueryName("product_for_location_select")),
DOCTOR_CHEMIST_INSERT(AdhocQueryName("doctor_chemist_insert")),
DOCTOR_CHEMIST_DELETE(AdhocQueryName("doctor_chemist_delete")),
HOSPITAL_BY_LOCATION_SELECT(AdhocQueryName("hospital_by_location_select")),
FIELD_STRUCTURE_SELECT(AdhocQueryName("field_structure_select")),
DML_STRUCTURE_SELECT(AdhocQueryName("dml_structure_select")),
HOLIDAYS_FOR_LOCATION_SELECT(AdhocQueryName("holidays_for_location_select")),
DML_CLASSIFICATION_SELECT(AdhocQueryName("dml_classification_select")),
LOCATION_TOWN_SELECT(AdhocQueryName("location_town_select")),
EMPLOYEE_PROFILE_LIST_SELECT(AdhocQueryName("employee_profile_for_period_select")),
APPROVAL_CHAIN_DELETE(AdhocQueryName("aprci_by_criteria_delete")),
APPROVAL_CHAIN_SELECT(AdhocQueryName("aprci_select")),
MY_ALL_TOWN_LIST_SELECT(AdhocQueryName("all_my_towns_select")),
DML_LOCATION_SELECT(AdhocQueryName("location_dml_select")),
ALL_LOCATION_SELECT(AdhocQueryName("all_locations_select")),
CHEMIST_COUNT_SELECT(AdhocQueryName("total_chemists_count_select")),
VALID_NOTIFICATION_SELECT(AdhocQueryName("notif_select")),
ETAGS_SELECT(AdhocQueryName("etags_select")),
ETAGR_SELECT(AdhocQueryName("etagr_select")),
LOCATION_HIERARCHY_SELECT(AdhocQueryName("location_hierarchy_select")),
APPROVAL_CHAIN_BY_TYPE_SELECT(AdhocQueryName("aprci_by_type_select")),
HOLIDAYS_BY_STATE_SELECT(AdhocQueryName("holidays_by_state_select")),
LOCATION_WISE_STATE_SELECT(AdhocQueryName("location_wise_state_select")),
BLOCKING_ENTRIES_SELECT(AdhocQueryName("blocking_entries_select"))
}
