export const INIT_DOCTOR_LIST_START = 'INIT_DOCTOR_LIST_START';
export const INIT_DOCTOR_LIST_SUCCESS = 'INIT_DOCTOR_LIST_SUCCESS';
export const INIT_DOCTOR_LIST_FAIL = 'INIT_DOCTOR_LIST_FAIL';

export const INIT_DOCTOR_ADD_START = 'INIT_DOCTOR_ADD_START';
export const INIT_DOCTOR_ADD_SUCCESS = 'INIT_DOCTOR_ADD_SUCCESS';
export const INIT_DOCTOR_ADD_FAIL = 'INIT_DOCTOR_ADD_FAIL';

export const SAVE_DOCTOR_START = 'SAVE_DOCTOR_START';
export const SAVE_DOCTOR_SUCCESS = 'SAVE_DOCTOR_SUCCESS';
export const SAVE_DOCTOR_FAIL = 'SAVE_DOCTOR_FAIL';
