export const CONSOLIDATED_REPORT_START = 'CONSOLIDATED_REPORT_START';
export const CONSOLIDATED_REPORT_SUCCESS = 'CONSOLIDATED_REPORT_SUCCESS';
export const CONSOLIDATED_REPORT_FAIL = 'CONSOLIDATED_REPORT_FAIL';