export const INIT_DIGITAL_CALL_START = 'INIT_DIGITAL_CALL_START';
export const INIT_DIGITAL_CALL_SUCCESS = 'INIT_DIGITAL_CALL_SUCCESS';
export const INIT_DIGITAL_CALL_FAIL = 'INIT_DIGITAL_CALL_FAIL';

export const SAVE_DIGITAL_CALL_START = 'SAVE_DIGITAL_CALL_START';
export const SAVE_DIGITAL_CALL_SUCCESS = 'SAVE_DIGITAL_CALL_SUCCESS';
export const SAVE_DIGITAL_CALL_FAIL = 'SAVE_DIGITAL_CALL_FAIL';
