export const CHANGE_CALL_STEP = 'CALL_CHANGE_CALL_STEP';

export const SET_JOINEES = 'SET_JOINEES';

export const CALL_SET_CALL_TYPE_LIST_START = 'CALL_SET_CALL_TYPE_LIST_START';
export const CALL_SET_CALL_TYPE_LIST_SUCCESS =
  'CALL_SET_CALL_TYPE_LIST_SUCCESS';
export const CALL_SET_CALL_TYPE_LIST_FAIL = 'CALL_SET_CALL_TYPE_LIST_FAIL';

export const CALL_INIT_DOCTOR_LIST_START = 'CALL_INIT_DOCTOR_LIST_START';
export const CALL_INIT_DOCTOR_LIST_SUCCESS = 'CALL_INIT_DOCTOR_LIST_SUCCESS';
export const CALL_INIT_DOCTOR_LIST_FAIL = 'CALL_INIT_DOCTOR_LIST_FAIL';

export const ZSM_CALL_CONFIRM_START = 'ZSM_CALL_CONFIRM_START';
export const ZSM_CALL_CONFIRM_SUCCESS = 'ZSM_CALL_CONFIRM_SUCCESS';
export const ZSM_CALL_CONFIRM_FAIL = 'ZSM_CALL_CONFIRM_FAIL';

export const CALL_INIT_NCA_LIST_START = 'CALL_INIT_NCA_LIST_START';
export const CALL_INIT_NCA_LIST_SUCCESS = 'CALL_INIT_NCA_LIST_SUCCESS';
export const CALL_INIT_NCA_LIST_FAIL = 'CALL_INIT_NCA_LIST_FAIL';

export const ADD_UNPLANNED_DOCTORS_START = 'ADD_UNPLANNED_DOCTORS_START';
export const ADD_UNPLANNED_DOCTORS_SUCCESS = 'ADD_UNPLANNED_DOCTORS_SUCCESS';
export const ADD_UNPLANNED_DOCTORS_FAIL = 'ADD_UNPLANNED_DOCTORS_FAIL';

export const ADD_UNPLANNED_NCA_START = 'ADD_UNPLANNED_NCA_START';
export const ADD_UNPLANNED_NCA_SUCCESS = 'ADD_UNPLANNED_NCA_SUCCESS';
export const ADD_UNPLANNED_NCA_FAIL = 'ADD_UNPLANNED_NCA_FAIL';

export const INIT_VISIT_DETAILS_START = 'INIT_VISIT_DETAILS_START';
export const INIT_VISIT_DETAILS_SUCCESS = 'INIT_VISIT_DETAILS_SUCCESS';
export const INIT_VISIT_DETAILS_FAIL = 'INIT_VISIT_DETAILS_FAIL';

export const SAVE_VISIT_TO_DB_START = 'SAVE_VISIT_TO_DB_START';
export const SAVE_VISIT_TO_DB_SUCCESS = 'SAVE_VISIT_TO_DB_SUCCESS';
export const SAVE_VISIT_TO_DB_END = 'SAVE_VISIT_TO_DB_END';

export const SAVE_DOCTOR_COORDINATES_START = 'SAVE_DOCTOR_COORDINATES_START';
export const SAVE_DOCTOR_COORDINATES_SUCCESS =
  'SAVE_DOCTOR_COORDINATES_SUCCESS';
export const SAVE_DOCTOR_COORDINATES_FAIL = 'SAVE_DOCTOR_COORDINATES_FAIL';

export const INIT_VISIT_COMMENTS_START = 'INIT_VISIT_COMMENTS_START';
export const INIT_VISIT_COMMENTS_SUCCESS = 'INIT_VISIT_COMMENTS_SUCCESS';
export const INIT_VISIT_COMMENTS_FAIL = 'INIT_VISIT_COMMENTS_FAIL';

export const RESET_CALL_START = 'RESET_CALL_START';
export const RESET_CALL_SUCCESS = 'RESET_CALL_SUCCESS';
export const RESET_CALL_FAIL = 'RESET_CALL_FAIL';
