export const INIT_EFFORT_REPORT_START = 'INIT_EFFORT_REPORT_START';
export const INIT_EFFORT_REPORT_SUCCESS = 'INIT_EFFORT_REPORT_SUCCESS';
export const INIT_EFFORT_REPORT_FAIL = 'INIT_EFFORT_REPORT_FAIL';

export const FETCH_EFFORT_REPORT_START = 'FETCH_EFFORT_REPORT_START';
export const FETCH_EFFORT_REPORT_SUCCESS = 'FETCH_EFFORT_REPORT_SUCCESS';
export const FETCH_EFFORT_REPORT_FAIL = 'FETCH_EFFORT_REPORT_FAIL';

export const EXPAND_EFFORT_REPORT_START = 'EXPAND_EFFORT_REPORT_START';
export const EXPAND_EFFORT_REPORT_SUCCESS = 'EXPAND_EFFORT_REPORT_SUCCESS';
export const EXPAND_EFFORT_REPORT_FAIL = 'EXPAND_EFFORT_REPORT_FAIL';

export const FETCH_DAILY_EFFORT_REPORT_START = 'FETCH_DAILY_EFFORT_REPORT_START';
export const FETCH_DAILY_EFFORT_REPORT_SUCCESS = 'FETCH_DAILY_EFFORT_REPORT_SUCCESS';
export const FETCH_DAILY_EFFORT_REPORT_FAIL = 'FETCH_DAILY_EFFORT_REPORT_FAIL';

export const FETCH_DOCTOR_VISIT_REPORT_START = 'FETCH_DOCTOR_VISIT_REPORT_START';
export const FETCH_DOCTOR_VISIT_REPORT_SUCCESS = 'FETCH_DOCTOR_VISIT_REPORT_SUCCESS';
export const FETCH_DOCTOR_VISIT_REPORT_FAIL = 'FETCH_DOCTOR_VISIT_REPORT_FAIL';

export const FETCH_DEVIATION_VISIT_REPORT_START = 'FETCH_DEVIATION_VISIT_REPORT_START';
export const FETCH_DEVIATION_VISIT_REPORT_SUCCESS = 'FETCH_DEVIATION_VISIT_REPORT_SUCCESS';
export const FETCH_DEVIATION_VISIT_REPORT_FAIL = 'FETCH_DEVIATION_VISIT_REPORT_FAIL';
