export const INIT_DASHBOARD_START = 'INIT_DASHBOARD_START';
export const INIT_DASHBOARD_SUCCESS = 'INIT_DASHBOARD_SUCCESS';
export const INIT_DASHBOARD_FAIL = 'INIT_DASHBOARD_START_FAIL';

export const LOAD_NOTIFICATIONS_START = 'LOAD_NOTIFICATIONS_START';
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_FAIL = 'LOAD_NOTIFICATIONS_FAIL';

export const LOAD_CRM_DASHBOARD_START = 'LOAD_CRM_DASHBOARD_START';
export const LOAD_CRM_DASHBOARD_SUCCESS = 'LOAD_CRM_DASHBOARD_SUCCESS';
export const LOAD_CRM_DASHBOARD_FAIL = 'LOAD_CRM_DASHBOARD_FAIL';

export const LOAD_CALL_DASHBOARD_START = 'LOAD_CALL_DASHBOARD_START';
export const LOAD_CALL_DASHBOARD_SUCCESS = 'LOAD_CALL_DASHBOARD_SUCCESS';
export const LOAD_CALL_DASHBOARD_FAIL = 'LOAD_CALL_DASHBOARD_FAIL';
