export const COVERAGE_REPORT_START = 'COVERAGE_REPORT_START';
export const COVERAGE_REPORT_SUCCESS = 'COVERAGE_REPORT_SUCCESS';
export const COVERAGE_REPORT_FAIL = 'COVERAGE_REPORT_FAIL';

export const MISSED_CALL_REPORT_START = 'MISSED_CALL_REPORT_START';
export const MISSED_CALL_REPORT_SUCCESS = 'MISSED_CALL_REPORT_SUCCESS';
export const MISSED_CALL_REPORT_FAIL = 'MISSED_CALL_REPORT_FAIL';
