export const FETCH_FIELD_STRUCTURE_START = 'FETCH_FIELD_STRUCTURE_START';
export const FETCH_FIELD_STRUCTURE_SUCCESS = 'FETCH_FIELD_STRUCTURE_SUCCESS';
export const FETCH_FIELD_STRUCTURE_FAIL = 'FETCH_FIELD_STRUCTURE_FAIL';
