export const TROUBLESHOOT_INIT_START = 'TROUBLESHOOT_INIT_START';
export const TROUBLESHOOT_INIT_SUCCESS = 'TROUBLESHOOT_INIT_SUCCESS';
export const TROUBLESHOOT_INIT_FAIL = 'TROUBLESHOOT_INIT_FAIL';
