export const INIT_DETAILING_BRAND_LIST_START =
  'INIT_DETAILING_BRAND_LIST_START';
export const INIT_DETAILING_BRAND_LIST_SUCCESS =
  'INIT_DETAILING_BRAND_LIST_SUCCESS';
export const INIT_DETAILING_BRAND_LIST_FAIL = 'INIT_DETAILING_BRAND_LIST_FAIL';

export const DOWNLOAD_DETAILING_START = 'DOWNLOAD_DETAILING_START';
export const DOWNLOAD_DETAILING_SUCCESS = 'DOWNLOAD_DETAILING_SUCCESS';
export const DOWNLOAD_DETAILING_FAIL = 'DOWNLOAD_DETAILING_FAIL';

export const LOAD_DETAILING_THUMBNAIL_START = 'LOAD_DETAILING_THUMBNAIL_START';
export const LOAD_DETAILING_THUMBNAIL_SUCCESS =
  'LOAD_DETAILING_THUMBNAIL_SUCCESS';
export const LOAD_DETAILING_THUMBNAIL_FAIL = 'LOAD_DETAILING_THUMBNAIL_FAIL';

export const SAVE_DETAILING_PRECALL_START = 'SAVE_DETAILING_PRECALL_START';
export const SAVE_DETAILING_PRECALL_SUCCESS = 'SAVE_DETAILING_PRECALL_SUCCESS';
export const SAVE_DETAILING_PRECALL_FAIL = 'SAVE_DETAILING_PRECALL_FAIL';

export const LOAD_VA_TO_DETAIL_START = 'LOAD_VA_TO_DETAIL_START';
export const LOAD_VA_TO_DETAIL_SUCCESS = 'LOAD_VA_TO_DETAIL_SUCCESS';
export const LOAD_VA_TO_DETAIL_FAIL = 'LOAD_VA_TO_DETAIL_FAIL';

export const INIT_PRE_CALL_PLANNING_START = 'INIT_PRE_CALL_PLANNING_START';
export const INIT_PRE_CALL_PLANNING_SUCCESS = 'INIT_PRE_CALL_PLANNING_SUCCESS';
export const INIT_PRE_CALL_PLANNING_FAIL = 'INIT_PRE_CALL_PLANNING_FAIL';

export const CLOSE_DETAILING_MODAL_START = 'CLOSE_DETAILING_MODAL_START';
export const CLOSE_DETAILING_MODAL_SUCCESS = 'CLOSE_DETAILING_MODAL_SUCCESS';
export const CLOSE_DETAILING_MODAL_FAIL = 'CLOSE_DETAILING_MODAL_FAIL';
